// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpillSense.Infrastructure.Persistence;

#nullable disable

namespace SpillSense.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SpillSenseDbContext))]
    [Migration("20260723234031_AddImportTracking")]
    partial class AddImportTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SpillSense.Domain.Geography.County", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FipsCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCoastal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FipsCode")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Counties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FipsCode = "53001",
                            IsCoastal = false,
                            Name = "Adams",
                            Region = "Eastern"
                        },
                        new
                        {
                            Id = 2,
                            FipsCode = "53003",
                            IsCoastal = false,
                            Name = "Asotin",
                            Region = "Eastern"
                        },
                        new
                        {
                            Id = 3,
                            FipsCode = "53005",
                            IsCoastal = false,
                            Name = "Benton",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 4,
                            FipsCode = "53007",
                            IsCoastal = false,
                            Name = "Chelan",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 5,
                            FipsCode = "53009",
                            IsCoastal = true,
                            Name = "Clallam",
                            Region = "Southwest"
                        },
                        new
                        {
                            Id = 6,
                            FipsCode = "53011",
                            IsCoastal = false,
                            Name = "Clark",
                            Region = "Southwest"
                        },
                        new
                        {
                            Id = 7,
                            FipsCode = "53013",
                            IsCoastal = false,
                            Name = "Columbia",
                            Region = "Eastern"
                        },
                        new
                        {
                            Id = 8,
                            FipsCode = "53015",
                            IsCoastal = false,
                            Name = "Cowlitz",
                            Region = "Southwest"
                        },
                        new
                        {
                            Id = 9,
                            FipsCode = "53017",
                            IsCoastal = false,
                            Name = "Douglas",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 10,
                            FipsCode = "53019",
                            IsCoastal = false,
                            Name = "Ferry",
                            Region = "Eastern"
                        },
                        new
                        {
                            Id = 11,
                            FipsCode = "53021",
                            IsCoastal = false,
                            Name = "Franklin",
                            Region = "Eastern"
                        },
                        new
                        {
                            Id = 12,
                            FipsCode = "53023",
                            IsCoastal = false,
                            Name = "Garfield",
                            Region = "Eastern"
                        },
                        new
                        {
                            Id = 13,
                            FipsCode = "53025",
                            IsCoastal = false,
                            Name = "Grant",
                            Region = "Eastern"
                        },
                        new
                        {
                            Id = 14,
                            FipsCode = "53027",
                            IsCoastal = true,
                            Name = "Grays Harbor",
                            Region = "Southwest"
                        },
                        new
                        {
                            Id = 15,
                            FipsCode = "53029",
                            IsCoastal = true,
                            Name = "Island",
                            Region = "Northwest"
                        },
                        new
                        {
                            Id = 16,
                            FipsCode = "53031",
                            IsCoastal = true,
                            Name = "Jefferson",
                            Region = "Southwest"
                        },
                        new
                        {
                            Id = 17,
                            FipsCode = "53033",
                            IsCoastal = true,
                            Name = "King",
                            Region = "Northwest"
                        },
                        new
                        {
                            Id = 18,
                            FipsCode = "53035",
                            IsCoastal = true,
                            Name = "Kitsap",
                            Region = "Northwest"
                        },
                        new
                        {
                            Id = 19,
                            FipsCode = "53037",
                            IsCoastal = false,
                            Name = "Kittitas",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 20,
                            FipsCode = "53039",
                            IsCoastal = false,
                            Name = "Klickitat",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 21,
                            FipsCode = "53041",
                            IsCoastal = false,
                            Name = "Lewis",
                            Region = "Southwest"
                        },
                        new
                        {
                            Id = 22,
                            FipsCode = "53043",
                            IsCoastal = false,
                            Name = "Lincoln",
                            Region = "Eastern"
                        },
                        new
                        {
                            Id = 23,
                            FipsCode = "53045",
                            IsCoastal = true,
                            Name = "Mason",
                            Region = "Southwest"
                        },
                        new
                        {
                            Id = 24,
                            FipsCode = "53047",
                            IsCoastal = false,
                            Name = "Okanogan",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 25,
                            FipsCode = "53049",
                            IsCoastal = true,
                            Name = "Pacific",
                            Region = "Southwest"
                        },
                        new
                        {
                            Id = 26,
                            FipsCode = "53051",
                            IsCoastal = false,
                            Name = "Pend Oreille",
                            Region = "Eastern"
                        },
                        new
                        {
                            Id = 27,
                            FipsCode = "53053",
                            IsCoastal = true,
                            Name = "Pierce",
                            Region = "Southwest"
                        },
                        new
                        {
                            Id = 28,
                            FipsCode = "53055",
                            IsCoastal = true,
                            Name = "San Juan",
                            Region = "Northwest"
                        },
                        new
                        {
                            Id = 29,
                            FipsCode = "53057",
                            IsCoastal = true,
                            Name = "Skagit",
                            Region = "Northwest"
                        },
                        new
                        {
                            Id = 30,
                            FipsCode = "53059",
                            IsCoastal = false,
                            Name = "Skamania",
                            Region = "Southwest"
                        },
                        new
                        {
                            Id = 31,
                            FipsCode = "53061",
                            IsCoastal = true,
                            Name = "Snohomish",
                            Region = "Northwest"
                        },
                        new
                        {
                            Id = 32,
                            FipsCode = "53063",
                            IsCoastal = false,
                            Name = "Spokane",
                            Region = "Eastern"
                        },
                        new
                        {
                            Id = 33,
                            FipsCode = "53065",
                            IsCoastal = false,
                            Name = "Stevens",
                            Region = "Eastern"
                        },
                        new
                        {
                            Id = 34,
                            FipsCode = "53067",
                            IsCoastal = true,
                            Name = "Thurston",
                            Region = "Southwest"
                        },
                        new
                        {
                            Id = 35,
                            FipsCode = "53069",
                            IsCoastal = false,
                            Name = "Wahkiakum",
                            Region = "Southwest"
                        },
                        new
                        {
                            Id = 36,
                            FipsCode = "53071",
                            IsCoastal = false,
                            Name = "Walla Walla",
                            Region = "Eastern"
                        },
                        new
                        {
                            Id = 37,
                            FipsCode = "53073",
                            IsCoastal = true,
                            Name = "Whatcom",
                            Region = "Northwest"
                        },
                        new
                        {
                            Id = 38,
                            FipsCode = "53075",
                            IsCoastal = false,
                            Name = "Whitman",
                            Region = "Eastern"
                        },
                        new
                        {
                            Id = 39,
                            FipsCode = "53077",
                            IsCoastal = false,
                            Name = "Yakima",
                            Region = "Central"
                        });
                });

            modelBuilder.Entity("SpillSense.Domain.Incidents.SpillIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CountyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuantityGallons")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RecoveredGallons")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsibleParty")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WaterbodyName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountyId");

                    b.HasIndex("ReportNumber")
                        .IsUnique();

                    b.HasIndex("ReportedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("SubstanceCategory");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("SpillIncidents", (string)null);
                });

            modelBuilder.Entity("SpillSense.Domain.Intake.ImportRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnchangedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("ImportRuns", (string)null);
                });

            modelBuilder.Entity("SpillSense.Domain.Intake.QuarantinedRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawRow")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId");

                    b.ToTable("QuarantinedRecords", (string)null);
                });

            modelBuilder.Entity("SpillSense.Domain.Incidents.SpillIncident", b =>
                {
                    b.HasOne("SpillSense.Domain.Geography.County", "County")
                        .WithMany()
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("County");
                });

            modelBuilder.Entity("SpillSense.Domain.Intake.QuarantinedRecord", b =>
                {
                    b.HasOne("SpillSense.Domain.Intake.ImportRun", "ImportRun")
                        .WithMany("QuarantinedRecords")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportRun");
                });

            modelBuilder.Entity("SpillSense.Domain.Intake.ImportRun", b =>
                {
                    b.Navigation("QuarantinedRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
